- README.md
- build.sbt
- language/src/main/scala/com/reactific/riddl/language/Logger.scala
- language/src/main/scala/com/reactific/riddl/language/SymbolTable.scala
- language/src/main/scala/com/reactific/riddl/language/Validation.scala
- project/Helpers.scala
- riddlc/src/main/scala/com/reactific/riddl/RIDDLC.scala
- testkit/src/main/scala/com/reactific/riddl/language/testkit/ParsingTest.scala
- testkit/src/test/scala/com/reactific/riddl/language/GherkinTest.scala
Fix a garden variety set of small issues:
* Add org.apache.commons.lang3 dependency for ExceptionUtils
* Make non-fatal exceptions turn into severe errors in riddlc
* Use Commons.Lang3.ExceptionUtils for generating full stack trace messages
* Provide full stack trace for non-fatal exceptions that happen during validation exceptions
* Add support for testing Gherkin Examples
* Update README.md to provide better usage instructions for active development of riddl models
* Fix validation for empty references and identifiers
> Omnibus Fixes

- build.sbt
- project/plugins.sbt
- riddlc/src/main/scala/com/reactific/riddl/RIDDLC.scala
- riddlc/src/main/scala/com/reactific/riddl/RiddlOptions.scala
* Upgrade to buildinfo 0.11.0
* Configure buildInfo into riddlc
* Add a command to print out
* Upgrade to scalac 2.13.8
> Add "info" command

- .github/workflows/gh-pages.yml
- doc/src/hugo/content/language/common/identifiers.md
- language/src/main/scala/com/reactific/riddl/language/Folding.scala
- language/src/main/scala/com/reactific/riddl/language/Validation.scala
- language/src/test/scala/com/reactific/riddl/language/PathResolutionSpec.scala
* Resolve paths through TypeRefs by expanding the stacks
* Allow workflows to trigger on more paths and manually
> Fix path resolution & workflow

- hugo-translator/src/main/scala/com/reactific/riddl/translator/hugo/HugoTranslator.scala
- language/src/main/scala/com/reactific/riddl/language/AST.scala
- language/src/main/scala/com/reactific/riddl/language/Validation.scala
- language/src/main/scala/com/reactific/riddl/language/ast/Abstract.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/CommonParser.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/ContextParser.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/DomainParser.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/EntityParser.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/StreamingParser.scala
- testkit/src/test/scala/com/reactific/riddl/language/StreamingParserTest.scala
* Allow AuthorInfo in Context, Entity, Story, Plant
* Organize the TODO list by Author
* Validate these changes yield no errors on improving.riddl test case
> Implement Author Based TODO list

- project/build.properties
- utils/src/main/scala/com/reactific/riddl/utils/Plugin.scala
* Put a synchronized block around loadSpecificPluginsFrom
* Upgrade to sbt 1.7.1
> Avoid intermittent test failures

- .scala-steward.com
- project/plugins.sbt
* Stop update checks for things with version dependency failures
* Slow down updates for things not directly related
* Update sbt-coverage to 1.9.3
> Scala Steward Configuration

- build.sbt
- commands/src/main/scala/com/reactific/riddl/commands/DumpCommand.scala
* Put the maintainer sbt var back
* Make "dump" actually print the AST
> Post-release fixes:

- commands/src/main/scala/com/reactific/riddl/commands/DumpCommand.scala
- riddlc/src/main/scala/com/reactific/riddl/AboutCommand.scala
- riddlc/src/main/scala/com/reactific/riddl/HelpCommand.scala
- riddlc/src/main/scala/com/reactific/riddl/RIDDLC.scala
- riddlc/src/main/scala/com/reactific/riddl/VersionCommand.scala
- riddlc/src/test/scala/com/reactific/riddl/RiddlCommandsTest.scala
- testkit/src/test/scala/com/reactific/riddl/language/FoldingTest.scala
- testkit/src/test/scala/com/reactific/riddl/language/GherkinTest.scala
- testkit/src/test/scala/com/reactific/riddl/language/RegressionTests.scala
- testkit/src/test/scala/com/reactific/riddl/language/TranslatorTest.scala
- testkit/src/test/scala/com/reactific/riddl/language/TypeParserTest.scala
- testkit/src/test/scala/com/reactific/riddl/language/ValidateExamplesTest.scala
- utils/src/main/scala/com/reactific/riddl/utils/Logger.scala
* Comment out "info(...) lines in test cases"
* Change to a StringLogger when --quiet is given
* Print out a summary count of message levels on --quiet
* Change test causes to use --quiet to not print out messages
* Change a few commands to not use println
> Reduce testing output

- commands/src/main/scala/com/reactific/riddl/commands/CommandOptions.scala
- commands/src/main/scala/com/reactific/riddl/commands/FromCommand.scala
- commands/src/test/scala/com/reactific/riddl/commands/CommonOptionsTest.scala
- commands/src/test/scala/com/reactific/riddl/commands/PluginCommandTest.scala
- riddlc/src/test/input/common-overrides.conf
- riddlc/src/test/scala/com/reactific/riddl/RiddlCommandsTest.scala
- testkit/src/test/input/hugo.conf
* support show/hide/suppress labels in config files
* ensure suppress/hide always override show
* Don't support overrides from the top level of config any more
* Fix a bug in computing the value to set
* Make sure the default value is always the last choice
* Fix tests
* Upgrade to 0.13.+
> Support Better Common Options Parsing

- .vale.ini
- build.sbt
- language/src/main/scala/com/reactific/riddl/language/Validation.scala
- project/Helpers.scala
- project/plugins.sbt
* Add the vale.ini file
* Add needed settings for Site Plugin
* Remove TODOs: story case validation
* Add maintainer setting
> Various cleanup tasks

- language/src/main/scala/com/reactific/riddl/language/Riddl.scala
- language/src/main/scala/com/reactific/riddl/language/Validation.scala
- language/src/test/scala/com/reactific/riddl/language/PathResolutionSpec.scala
- testkit/src/main/scala/com/reactific/riddl/testkit/ValidatingTest.scala
- testkit/src/test/scala/com/reactific/riddl/language/CheckMessagesTest.scala
- testkit/src/test/scala/com/reactific/riddl/language/DomainValidatorTest.scala
> Implement Uses/Used-By Pass

- language/src/main/scala/com/reactific/riddl/language/Validation.scala
- language/src/test/scala/com/reactific/riddl/language/UsageSpec.scala
- testkit/src/test/input/check/ambiguity/ambiguity.check
- testkit/src/test/input/check/everything/everything.check
- testkit/src/test/input/check/overloading/overloading.check
- testkit/src/test/input/check/saga/saga.check
- testkit/src/test/input/check/simpleDomain.riddl
- testkit/src/test/scala/com/reactific/riddl/language/EntityValidatorTest.scala
- testkit/src/test/scala/com/reactific/riddl/language/FunctionValidatorTest.scala
- testkit/src/test/scala/com/reactific/riddl/language/TypeValidatorTest.scala
> #201 Implement unused checking for entities, types, functions

- doc/src/hugo/content/guides/developers/releasing.md
> Fix release instructions

- build.sbt
- project/Helpers.scala
> Restore ability to use scoverage

- hugo/src/main/resources/hugo/layouts/partials/head/custom.html
> Generate Graphical Table Of Contents

- hugo/src/main/scala/com/reactific/riddl/hugo/HugoTranslator.scala
- hugo/src/main/scala/com/reactific/riddl/hugo/SequenceDiagrammer.scala
- hugo/src/test/input/regressions/match-error.riddl
- language/src/main/scala/com/reactific/riddl/language/AST.scala
- language/src/main/scala/com/reactific/riddl/language/Validation.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/ActionParser.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/SagaParser.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/StoryParser.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/Terminals.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/UIParser.scala
- language/src/test/scala/com/reactific/riddl/language/ApplicationTest.scala
- language/src/test/scala/com/reactific/riddl/language/StoryTest.scala
* Include app components in validation
* Fix test case syntax
> Limit stories to working with application components

- doc/src/hugo/content/concepts/message.md
- doc/src/hugo/content/concepts/repository.md
- language/src/main/scala/com/reactific/riddl/language/AST.scala
- language/src/main/scala/com/reactific/riddl/language/Finder.scala
- language/src/main/scala/com/reactific/riddl/language/Validation.scala
- language/src/main/scala/com/reactific/riddl/language/ast/AbstractDefinitions.scala
- language/src/main/scala/com/reactific/riddl/language/ast/Options.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/ContextParser.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/RepositoryParser.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/StoryParser.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/StreamingParser.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/Terminals.scala
- language/src/test/scala/com/reactific/riddl/language/RepositoryTest.scala
- project/build.properties
* Documentation addition
* Make *Definition traits sealed for finding bugs in AST
* Add RepositoryParser for parsing them
* Add Repository to the finder
* Validate repositories and fix missing definitions resulting from new sealed traits
> Add "Repository" concept

- commands/src/main/scala/com/reactific/riddl/commands/CommandPlugin.scala
- hugo/src/main/scala/com/reactific/riddl/hugo/MarkdownWriter.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/ApplicationParser.scala
- riddlc/src/main/scala/com/reactific/riddl/AboutCommand.scala
- riddlc/src/main/scala/com/reactific/riddl/HelpCommand.scala
- riddlc/src/main/scala/com/reactific/riddl/InfoCommand.scala
- riddlc/src/main/scala/com/reactific/riddl/VersionCommand.scala
- riddlc/src/test/input/cmdoptions.conf
- riddlc/src/test/scala/com/reactific/riddl/OptionsReadingTest.scala
- riddlc/src/test/scala/com/reactific/riddl/RiddlcCommandsTest.scala
- testkit/src/main/scala/com/reactific/riddl/testkit/ParsingTest.scala
- testkit/src/test/scala/com/reactific/riddl/testkit/ParsingTestTest.scala
> Remove code smells & add coverage

- language/src/main/scala/com/reactific/riddl/language/AST.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/GherkinParser.scala
- testkit/src/main/scala/com/reactific/riddl/testkit/ParsingTest.scala
- testkit/src/main/scala/com/reactific/riddl/testkit/ValidatingTest.scala
- testkit/src/test/scala/com/reactific/riddl/testkit/ParsingTestTest.scala
> Improve TestKist Coverage

- prettify/src/test/scala/com/reactific/riddl/prettify/PrettifyCommandTest.scala
Add a test suite for PrettifyCommand
> Increase Prettify Coverage

- utils/src/test/scala/com/reactific/riddl/utils/InterruptTest.scala
> Disable a run-forever test

- language/src/main/scala/com/reactific/riddl/language/AST.scala
- language/src/main/scala/com/reactific/riddl/language/ast/Options.scala
- language/src/test/scala/com/reactific/riddl/language/ASTTest.scala
> Improve AST test coverage

- language/src/main/scala/com/reactific/riddl/language/parsing/CommonParser.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/DomainParser.scala
- language/src/main/scala/com/reactific/riddl/language/parsing/Terminals.scala
Make the parser recognize the "external" option in a domain so modeling of external domains can be managed.
> Domain external option

- language/src/main/scala/com/reactific/riddl/language/validation/DefinitionValidationState.scala
- language/src/test/scala/com/reactific/riddl/language/RegressionTests.scala
> fix: #359 - show the duplicates in the error!

- build.sbt
- doc/src/hugo/config.toml
- language/src/main/scala/com/reactific/riddl/language/parsing/TypeParser.scala
- project/Helpers.scala
- project/build.properties
- sbt-riddl/src/main/scala/com/reactific/riddl/sbt/plugin/RiddlSbtPlugin.scala
Avoid scala3doc hang when generating language documentation, to be fixed later, maybe.
> Fix doc gen

- .github/workflows/scala.yml
- actions/get-riddlc/action.yaml
- build.sbt
This PR makes the default action use 0.27.1 and archives the scoverage-report directory for successful builds
> Update action & scoverage Report

- language/src/test/input/snippets/application/emptiness.riddl
- language/src/test/scala/com/reactific/riddl/language/parsing/ApplicationParsingTest.scala
- passes/src/test/scala/com/reactific/riddl/passes/resolve/ResolutionPassTest.scala
Add a test suite that validates group/page definitions must have ??? in their otherwise empty body
> 479 empty pages

- .github/workflows/scala.yml
- README.md
- actions/get-riddlc/action.yaml
- build.sbt
- doc/src/hugo/config.toml
- doc/src/hugo/content/guides/developers/releasing.md
- doc/src/hugo/content/guides/implementors/ways-to-use-riddl.md
- doc/src/hugo/content/introduction/how-can-i-get-help.md
- doc/src/hugo/content/introduction/what-is-riddl.md
- doc/src/hugo/content/introduction/who-made-riddl-possible.md
- doc/src/hugo/content/reactive-summit.md
- doc/src/hugo/content/tooling/riddlc/build.md
- doc/src/hugo/content/tooling/riddlc/command-line-help.md
- doc/src/hugo/content/tooling/riddlc/download-and-use-a-release.md
- doc/src/hugo/content/tooling/riddlc/using-the-get-riddlc-action.md
- doc/src/hugo/content/tooling/sbt-riddl/_index.md
- doc/src/hugo/content/tutorial/rbbq/ReactiveBBQ.md
- doc/src/hugo/content/tutorial/rbbq/backoffice/_index.md
- doc/src/hugo/content/tutorial/rbbq/corporate/_index.md
- doc/src/hugo/content/tutorial/rbbq/restaurant/_index.md
- hugo/src/test/scala/com/ossuminc/riddl/hugo/MarkdownWriterTest.scala
- language/src/main/scala/com/ossuminc/riddl/language/parsing/CommonParser.scala
- passes/src/test/scala/com/ossuminc/riddl/passes/validate/DomainValidatorTest.scala
- riddlc/src/test/scala/com/ossuminc/riddl/RunRiddlcOnArbitraryTest.scala
- sbt-riddl/src/main/scala/com/ossuminc/riddl/sbt/plugin/RiddlSbtPlugin.scala
- sbt-riddl/src/sbt-test/sbt-riddl/simple/project/plugins.sbt
- sbt-riddl/src/sbt-test/sbt-riddl/simple/src/test/scala/com/reactific/test/GenerateTestSiteSpec.scala
- testkit/src/main/scala/com/ossuminc/riddl/testkit/RunCommandOnExamplesTest.scala
- testkit/src/test/input/hugo.conf
- testkit/src/test/scala/com/ossuminc/riddl/testkit/IncludeAndImportTest.scala
> Change remaining places that refer

- hugo/src/test/scala/com/ossuminc/riddl/hugo/RegressionTests.scala
- language/src/main/scala/com/ossuminc/riddl/language/AST.scala
- language/src/main/scala/com/ossuminc/riddl/language/parsing/CommonParser.scala
- language/src/main/scala/com/ossuminc/riddl/language/parsing/EpicParser.scala
- language/src/main/scala/com/ossuminc/riddl/language/parsing/Keywords.scala
- language/src/main/scala/com/ossuminc/riddl/language/parsing/NoWhiteSpaceParsers.scala
- language/src/test/scala/com/ossuminc/riddl/language/parsing/ParserTest.scala
- passes/src/main/scala/com/ossuminc/riddl/passes/resolve/ResolutionPass.scala
- passes/src/main/scala/com/ossuminc/riddl/passes/symbols/SymbolsPass.scala
- passes/src/main/scala/com/ossuminc/riddl/passes/validate/ValidationPass.scala
- riddlc/src/test/scala/com/ossuminc/riddl/RunRiddlcOnArbitraryTest.scala
- testkit/src/test/input/issues/480b.riddl
- testkit/src/test/scala/com/ossuminc/riddl/testkit/ReportedIssuesTest.scala
* make /* ... */ style comments available too so that they can be inserted ahead of delimiters because // goes to end of line
* Add FocusOnPageInteraction in AST and parser
> #480 Remove Includes From SymbolTable, & etc.

- build.sbt
- hugo/src/main/scala/com/ossuminc/riddl/hugo/MarkdownWriter.scala
- hugo/src/test/scala/com/ossuminc/riddl/hugo/ToDoPassListTest.scala
- language/src/main/scala/com/ossuminc/riddl/language/AST.scala
- language/src/main/scala/com/ossuminc/riddl/language/parsing/DomainParser.scala
- language/src/main/scala/com/ossuminc/riddl/language/parsing/EntityParser.scala
- language/src/main/scala/com/ossuminc/riddl/language/parsing/ParsingContext.scala
- language/src/main/scala/com/ossuminc/riddl/language/parsing/RiddlOptions.scala
- language/src/test/scala/com/ossuminc/riddl/language/ASTTest.scala
- language/src/test/scala/com/ossuminc/riddl/language/parsing/ParsingTest.scala
- language/src/test/scala/com/ossuminc/riddl/language/parsing/TestParser.scala
- prettify/src/main/scala/com/ossuminc/riddl/prettify/PrettifyPass.scala
- prettify/src/test/scala/com/ossuminc/riddl/prettify/PrettifyTest.scala
- testkit/src/main/scala/com/ossuminc/riddl/testkit/ParsingTest.scala
A partial implementation of #521:
* Merged RiddlNode and RiddlValue
* Turned on the -explain scalac option in language module where it's most useful
* Rearranged definitions to be more clear to the reader
* Documented things a little better
> 521 simplify ast

- language/src/main/scala/com/ossuminc/riddl/language/AST.scala
- language/src/main/scala/com/ossuminc/riddl/language/parsing/Keywords.scala
- language/src/main/scala/com/ossuminc/riddl/language/parsing/StatementParser.scala
- language/src/test/scala/com/ossuminc/riddl/language/parsing/ApplicationParsingTest.scala
- passes/src/main/scala/com/ossuminc/riddl/passes/resolve/ResolutionPass.scala
- passes/src/main/scala/com/ossuminc/riddl/passes/validate/ValidationPass.scala
> 530 focus statement

- build.sbt
- project/plugins.sbt
This upgrades scala to 3.3.3 and
removes WartRemover
> Upgrade to sbt-ossuminc 0.8.2

- language/src/main/scala/com/ossuminc/riddl/language/AST.scala
- language/src/main/scala/com/ossuminc/riddl/language/parsing/NoWhiteSpaceParsers.scala
- language/src/main/scala/com/ossuminc/riddl/language/parsing/StatementParser.scala
- passes/src/main/scala/com/ossuminc/riddl/passes/resolve/ResolutionPass.scala
- passes/src/main/scala/com/ossuminc/riddl/passes/validate/ValidationPass.scala
- riddlc/src/test/scala/com/ossuminc/riddl/RunRiddlcOnLocalTest.scala
- testkit/src/test/input/everything.riddl
* Allow ```lang ... ``` kind of syntax
* Translate that to a CodeStatement
> Implement the Code Statement

- commands/src/main/scala/com/ossuminc/riddl/commands/StatsCommand.scala
- hugo/src/main/scala/com/ossuminc/riddl/hugo/Summarizer.scala
* Format the output into columns
> Finish Stats Command

- .github/workflows/scala.yml
- README.md
- build.sbt
- project/plugins.sbt
* Upgrade to sbt-ossuminc 0.14.1 to get MiMa support
* Change scala.yml to invoke MiMa commands after build
* Set the previous version to 0.52.1
* Filter out problems with RiddlBuildInfo which is generated
* Fix a bug in ParseCommand
* Test with the new institutional-commerce app
> Support MiMa and Tasty-MiMa On Builds

- build.sbt
- language/jvm/src/test/scala/com/ossuminc/riddl/language/parsing/ProjectorTest.scala
- language/jvm/src/test/scala/com/ossuminc/riddl/language/parsing/RepositoryTest.scala
- language/shared/src/main/scala/com/ossuminc/riddl/language/AST.scala
- language/shared/src/main/scala/com/ossuminc/riddl/language/parsing/Keywords.scala
- language/shared/src/main/scala/com/ossuminc/riddl/language/parsing/ProcessorParser.scala
- language/shared/src/test/scala/com/ossuminc/riddl/language/ASTTest.scala
- passes/jvm/src/test/input/everything.riddl
- passes/jvm/src/test/scala/com/ossuminc/riddl/passes/VisitingPassTest.scala
- passes/shared/src/main/scala/com/ossuminc/riddl/passes/Pass.scala
- passes/shared/src/main/scala/com/ossuminc/riddl/passes/prettify/PrettifyVisitor.scala
> Implement relationship with test cases

- language/shared/src/main/scala/com/ossuminc/riddl/language/parsing/Keywords.scala
- language/shared/src/main/scala/com/ossuminc/riddl/language/parsing/Punctuation.scala
- language/shared/src/main/scala/com/ossuminc/riddl/language/parsing/Readability.scala
- language/shared/src/test/scala/com/ossuminc/riddl/language/parsing/KeywordsTest.scala
Also added a simple test case to stabilize the
keywords by count.
> #675 Provide lists of keywords, punctuation, readability
