language/src/main/scala/com/reactific/riddl/language/AST.scala, language/src/main/scala/com/reactific/riddl/language/Terminals.scala, language/src/main/scala/com/reactific/riddl/language/Validation.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ExpressionParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/TypeParser.scala, testkit/src/test/scala/com/reactific/riddl/language/ConditionParserTest.scala, testkit/src/test/scala/com/reactific/riddl/language/ExpressionParserTest.scala, testkit/src/test/scala/com/reactific/riddl/language/ParserTest.scala, testkit/src/test/scala/com/reactific/riddl/language/TypeParserTest.scala
- New syntax for defining message types with just
the message kind keyword
- Test case to test new syntax: "command foo is { a: Integer }"
- Correct naming of conditions that are expressions
- Reorganize ExpressionParser for comprehension
- Add AggregateConstructionExpression and its parser to support
creating Aggregates and Messages in expressions
=> Type & Expression Updates

language/src/main/scala/com/reactific/riddl/language/AST.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ContextParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/StreamingParser.scala, testkit/src/test/scala/com/reactific/riddl/language/StreamingParserTest.scala
- All PlantDefinitions also became ContextDefinitions
- Refactored StreamingParser to allow ContextParser
to use plantDefinition (singular)
- Added a test case for a Source in a Context
- Fixed inlet and outlet optional entity integration direction
=> Allow PlantDefinitions in Contexts

README.md, hugo-translator/src/main/scala/com/reactific/riddl/translator/hugo/HugoTranslator.scala, hugo-translator/src/main/scala/com/reactific/riddl/translator/hugo/MarkdownWriter.scala, language/src/main/scala/com/reactific/riddl/language/AST.scala, language/src/main/scala/com/reactific/riddl/language/ReformatTranslator.scala, language/src/main/scala/com/reactific/riddl/language/parsing/DomainParser.scala, riddlc/src/main/scala/com/reactific/riddl/RiddlOptions.scala, riddlc/src/test/scala/com/reactific/riddl/RiddlOptionsTest.scala, testkit/src/test/scala/com/reactific/riddl/language/DomainValidatorTest.scala, testkit/src/test/scala/com/reactific/riddl/language/ParserTest.scala, testkit/src/test/scala/com/reactific/riddl/language/TopLevelParserTest.scala
Allow multiple authors:
* Domains can now have multiple named author definitions, and
they don't have to come first in the domain.
Fix Hugo Processing & Authors:
* Added options for the site title and description
* Removed the siteLogo option since it can just be put in
the static directory instead of loaded from a URL
* Made riddlc actually read the "with" options for hugo cmd
* Always create the hugo output dir if it doesn't exist
* Handle the siteLogoPath option properly
* Simplify the function that generates the config.toml from a template
Update README:
* Add missing path element in Getting Started section of README
* Add instructions for using sbt-riddl plugin
=> Hugo improvements

build.sbt, commands/src/main/scala/com/reactific/riddl/commands/CommandPlugin.scala, commands/src/main/scala/com/reactific/riddl/commands/RepeatCommand.scala, commands/src/main/scala/com/reactific/riddl/commands/TranslationCommand.scala, doc/src/hugo/content/audience/developers-guide/releasing.md, git-check/src/main/scala/com/reactific/riddl/translator/hugo_git_check/GitCheckCommand.scala, hugo/src/main/scala/com/reactific/riddl/hugo/HugoCommand.scala, hugo/src/main/scala/com/reactific/riddl/hugo/MarkdownWriter.scala, project/Helpers.scala, project/plugins.sbt, riddlc/src/main/scala/com/reactific/riddl/HelpCommand.scala, riddlc/src/main/scala/com/reactific/riddl/InfoCommand.scala, riddlc/src/main/scala/com/reactific/riddl/RiddlOptions.scala, riddlc/src/test/scala/com/reactific/riddl/RiddlCommandsTest.scala, testkit/src/main/scala/com/reactific/riddl/language/testkit/RunCommandOnExamplesTest.scala
* Make the `help` output more readable
* Include "copyright" in the BuildInfo
* Use "copyright" in the `info` command
* Simplify build.sbt
* Remove unworkable code references in doc comments
* Update the releasing.md file to use "stage" command earlly to find
documentation issues.
* Prepare for Scala 3.2 upgrade (waiting on fastparse)
* Apply scala options consistently across project
* Fix syntax errors from -xsource:3 option
* Add the sbt-unidoc plugin
*
=> Various Improvements

commands/src/main/scala/com/reactific/riddl/commands/TranslationCommand.scala, language/src/main/scala/com/reactific/riddl/language/AST.scala, language/src/main/scala/com/reactific/riddl/language/Validation.scala, language/src/main/scala/com/reactific/riddl/language/ast/Expressions.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ActionParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ExpressionParser.scala, testkit/src/test/scala/com/reactific/riddl/language/ConditionParserTest.scala, testkit/src/test/scala/com/reactific/riddl/language/ExpressionParserTest.scala, testkit/src/test/scala/com/reactific/riddl/language/ParserTest.scala
* Add an expressionType member to each expression
* Default the expressionType for each expression
* In validation, use defaults except when PathIdentifiers are used
* Specify a few well-known and typed expressions
* Various other fixes
=> Make Expressions Typed

.github/workflows/scala.yml, build.sbt, project/Helpers.scala, riddlc/src/native-image.resources, utils/src/main/scala/com/reactific/riddl/utils/PathUtils.scala
The native-image tool doesn't include resources
in the image by default. You have to help it with a configuration file. Also, generate a better error message (requirement failed) when a resource cannot be loaded (instead of NPE)
=> Include resources in native image

hugo/src/main/scala/com/reactific/riddl/hugo/MarkdownWriter.scala, language/src/main/scala/com/reactific/riddl/language/AST.scala, language/src/main/scala/com/reactific/riddl/language/Folding.scala, language/src/main/scala/com/reactific/riddl/language/Validation.scala, language/src/main/scala/com/reactific/riddl/language/ast/TypeExpression.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ProjectionParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/Terminals.scala, language/src/main/scala/com/reactific/riddl/language/parsing/TypeParser.scala, language/src/test/scala/com/reactific/riddl/language/ContextValidationTest.scala, language/src/test/scala/com/reactific/riddl/language/StoryTest.scala, language/src/test/scala/com/reactific/riddl/language/TypeExpressionTest.scala, language/src/test/scala/com/reactific/riddl/language/TypeParserTest.scala, language/src/test/scala/com/reactific/riddl/language/UsageSpec.scala, prettify/src/main/scala/com/reactific/riddl/prettify/RiddlFileEmitter.scala, project/plugins.sbt
Projections are now defined as a sequence of type definitions (including the new "Record" case) followed by handlers, includes, and terms. This change allows that structure to compile correctly. Validation of these changes has not been completed.
=> #329 Revise projection parsing

language/src/main/scala/com/reactific/riddl/language/ast/AbstractDefinitions.scala, language/src/main/scala/com/reactific/riddl/language/ast/Definitions.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ReferenceParser.scala, language/src/main/scala/com/reactific/riddl/language/passes/resolve/KindMap.scala, language/src/main/scala/com/reactific/riddl/language/passes/resolve/ResolutionPass.scala, language/src/main/scala/com/reactific/riddl/language/passes/validate/BasicValidation.scala, language/src/main/scala/com/reactific/riddl/language/passes/validate/StreamingValidation.scala, language/src/main/scala/com/reactific/riddl/language/passes/validate/ValidationPass.scala, language/src/test/scala/com/reactific/riddl/language/parsing/CommonParserTest.scala, language/src/test/scala/com/reactific/riddl/language/parsing/ConditionParserTest.scala, language/src/test/scala/com/reactific/riddl/language/parsing/ExpressionParserTest.scala, language/src/test/scala/com/reactific/riddl/language/parsing/ParserTest.scala, language/src/test/scala/com/reactific/riddl/language/parsing/StreamingParserTest.scala, language/src/test/scala/com/reactific/riddl/language/parsing/TopLevelParserTest.scala, language/src/test/scala/com/reactific/riddl/language/parsing/TypeParserTest.scala, language/src/test/scala/com/reactific/riddl/language/passes/validate/HandlerValidatorTest.scala
It is more accurate to name and reference the message an On Clause is processing than to refer to its type. Allow this syntax:
`on event t:Type { ... }`
Actions can then refer to "t" as a local field to extract data from the provided message
=> Implemented named on clause messages

language/src/main/scala/com/reactific/riddl/language/ast/Definitions.scala, language/src/main/scala/com/reactific/riddl/language/parsing/AdaptorParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ApplicationParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ExpressionParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ProjectorParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/RepositoryParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/StreamingParser.scala, language/src/test/scala/com/reactific/riddl/language/ParsingTest.scala, language/src/test/scala/com/reactific/riddl/language/parsing/StreamingParserTest.scala, language/src/test/scala/com/reactific/riddl/language/passes/validate/ContextValidationTest.scala, language/src/test/scala/com/reactific/riddl/language/passes/validate/FunctionValidatorTest.scala
It was always the intention to allow functions wherever a handler definition could occur. Unfortunately, they were omitted from Adaptors, Applications, Projections, Repositories, and Streamlets. This patch rectifies that situation.
=> fix: Allow function definitions in more places

testkit/src/test/input/issues/375.riddl, testkit/src/test/scala/com/reactific/riddl/testkit/ReportedIssuesTest.scala
This issue #375 alleges that errors are missing from the provided input. This patch proves the opposite.
=> Path Validation not broken in 0.23.0+ 

build.sbt, language/src/main/scala/com/reactific/riddl/language/AST.scala, language/src/main/scala/com/reactific/riddl/language/ast/Actions.scala, language/src/main/scala/com/reactific/riddl/language/ast/Definitions.scala, language/src/main/scala/com/reactific/riddl/language/ast/Expressions.scala, language/src/main/scala/com/reactific/riddl/language/ast/Options.scala, language/src/main/scala/com/reactific/riddl/language/ast/Types.scala
The scalac bug appears to be an exponential complexity explosion caused by deep inheritance heirarchies. Using self types upsets it less. Generation takes ~200s locally, but at least completes.
=> Workaround for scalac bug preventing scaladoc gen

language/src/main/scala/com/reactific/riddl/language/ast/Definitions.scala, language/src/main/scala/com/reactific/riddl/language/ast/Statements.scala, language/src/main/scala/com/reactific/riddl/language/parsing/AdaptorParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ApplicationParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/CommonParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ContextParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/DomainParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/EntityParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/EpicParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/FunctionParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/HandlerParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ProjectorParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/RepositoryParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/SagaParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/StreamingParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/TopLevelParser.scala, language/src/test/input/domains/simpleDomain.riddl, language/src/test/scala/com/reactific/riddl/language/parsing/ParserTest.scala, language/src/test/scala/com/reactific/riddl/language/parsing/TopLevelParserTest.scala, passes/src/test/scala/com/reactific/riddl/passes/validate/ContextValidationTest.scala, passes/src/test/scala/com/reactific/riddl/passes/validate/EntityValidatorTest.scala, passes/src/test/scala/com/reactific/riddl/passes/validate/RegressionTests.scala, prettify/src/test/scala/com/reactific/riddl/prettify/PrettifyTest.scala, testkit/src/test/input/check/t0001/main.check, testkit/src/test/input/check/t0001/main.riddl, testkit/src/test/input/domains/simpleDomain.riddl, testkit/src/test/input/petstore.riddl, testkit/src/test/scala/com/reactific/riddl/testkit/ExamplesTest.scala, testkit/src/test/scala/com/reactific/riddl/testkit/IncludeAndImportTest.scala, testkit/src/test/scala/com/reactific/riddl/testkit/ReportedIssuesTest.scala
With this change:
* You can't make a definition body be "{ }" any more
* To get an empty definition, use "{ ??? }"
* Cuts have been added to generate better error messages
* Files with all syntax errors will not be silently ignored
This improves the error messages when junk occurs and eliminates the possibility of an included file being returned as an empty success.
=> Don't allow empty definition bodies

hugo/src/test/input/regressions/match-error.riddl, language/src/main/scala/com/reactific/riddl/language/AST.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ApplicationParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ReferenceParser.scala, passes/src/test/scala/com/reactific/riddl/passes/validate/ApplicationTest.scala, passes/src/test/scala/com/reactific/riddl/passes/validate/EpicTest.scala, testkit/src/test/input/issues/445.riddl, testkit/src/test/scala/com/reactific/riddl/testkit/ReportedIssuesTest.scala
Also:
* Don't allow type definitions in inputs, outputs or groups
* adjust syntax so body of input or output don't require { and }
* Fix test cases for new input and output syntax
* Add a test case to the ReportedIssues test suite to prevent regression
=> Allow groups to be the target of a from/to epic step

language/src/main/scala/com/reactific/riddl/language/AST.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ApplicationParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/CommonParser.scala, language/src/main/scala/com/reactific/riddl/language/parsing/ReferenceParser.scala, passes/src/main/scala/com/reactific/riddl/passes/validate/BasicValidation.scala, passes/src/main/scala/com/reactific/riddl/passes/validate/ValidationPass.scala, testkit/src/test/input/issues/447.riddl, testkit/src/test/scala/com/reactific/riddl/testkit/ReportedIssuesTest.scala
* groups/inputs/outputs remain the same but can have new alias names for syntactic sugar:
* for groups :  "page", "pane", "dialog", "popup", "frame", "column", "window", "section", "tab", "panel", "modal"
* for outputs:  "document", "list", "table"
* for inputs: "form", "text", "button", "picklist"
* groups can already nest in groups but it should be possible to allow inputs to have inputs and outputs to have outputs 
* ability to send output of context calls to an input, e.g. sending validation data to a modal written like:
`step take input from Form to context EntityContext.Entity`,  and outputs to Notification
* Allow inputs and outputs to handle any data type not just messages
* When input is sent to contexts or other backend definitions, they can only be commands and queries
* When …
=> Validate that messages to vital messages and their return messages

language/src/main/scala/com/reactific/riddl/language/AST.scala, language/src/main/scala/com/reactific/riddl/language/parsing/EntityParser.scala, language/src/test/scala/com/reactific/riddl/language/parsing/ParserTest.scala, passes/src/main/scala/com/reactific/riddl/passes/Pass.scala, passes/src/main/scala/com/reactific/riddl/passes/Riddl.scala, passes/src/main/scala/com/reactific/riddl/passes/resolve/ResolutionPass.scala, passes/src/main/scala/com/reactific/riddl/passes/symbols/SymbolsOutput.scala, passes/src/main/scala/com/reactific/riddl/passes/validate/BasicValidation.scala, passes/src/main/scala/com/reactific/riddl/passes/validate/StreamingValidation.scala, passes/src/main/scala/com/reactific/riddl/passes/validate/ValidationPass.scala, passes/src/test/scala/com/reactific/riddl/passes/validate/DomainValidatorTest.scala, passes/src/test/scala/com/reactific/riddl/passes/validate/HandlerValidatorTest.scala, passes/src/test/scala/com/reactific/riddl/passes/validate/StatementValidatorTest.scala, passes/src/test/scala/com/reactific/riddl/passes/validate/ValidatingTest.scala, passes/src/test/scala/com/reactific/riddl/passes/validate/ValidationPassTest.scala, testkit/src/main/scala/com/reactific/riddl/testkit/ValidatingTest.scala, testkit/src/test/input/check/everything/everything.riddl, testkit/src/test/input/check/references/bad-pids.check, testkit/src/test/input/issues/406.riddl
* You can no longer define types in side state definitions
* Foreach statements are now validated to ensure the referenced value has a type with cardinality
* Fix a bug with references to processors
* Fix a bug with cross-context validation
* Fix a bug with statement references not being checked when they occur within an on-message clause
* Fix a wrong-parentage bug with resolving statement references
* Fix an "empty on .last" problem
* Fix a bug in checkThatPathIdMatchesFoundParentStack
* Remove unused code
* Allow "contextOf" to match the definition, if it is a Context!
* Implement a style warning for cross-context references
* Implement validation of statements in all On Clauses
* Rename Pass.apply to Pass.runStandardPasses for clarity
* Add a StatementValidatorTest case
* Fix a bug in …
=> Fix statement validation and resolution

passes/src/main/scala/com/reactific/riddl/passes/resolve/ResolutionPass.scala, passes/src/main/scala/com/reactific/riddl/passes/symbols/SymbolsPass.scala, riddlc/src/test/scala/com/reactific/riddl/RunRiddlcOnArbitraryTest.scala
If the multiple results from the symbol table only differ by the path to the same definition then
there is no ambiguity. This can happen because of
implicit definitions (includes).
Also, if a non-implicit unnamed entry in the symbol table occurs, make sure it generates an error
Also, add a new Arbitrary local test for the
kalix-improving-template project.
=> Handle symtab case for path resolution

hugo/src/main/scala/com/ossuminc/riddl/hugo/MarkdownWriter.scala
Format doubles as %1.3f and precentages as %1.2f
=> Fix Statistics Table Width

language/src/main/scala/com/ossuminc/riddl/language/AST.scala, language/src/main/scala/com/ossuminc/riddl/language/parsing/ApplicationParser.scala, language/src/main/scala/com/ossuminc/riddl/language/parsing/Readability.scala, language/src/test/scala/com/ossuminc/riddl/language/parsing/ApplicationParsingTest.scala
This allows figma references to be made for pages and other larger portions of the application.
=> Implement "shown by" for application groups

.scalafix.conf, build.sbt, commands/src/main/scala/com/ossuminc/riddl/commands/CommandOptions.scala, commands/src/main/scala/com/ossuminc/riddl/commands/RepeatCommand.scala, diagrams/src/main/scala/com/ossuminc/riddl/diagrams/mermaid/UseCaseDiagram.scala, hugo/src/main/scala/com/ossuminc/riddl/hugo/HugoPass.scala, hugo/src/main/scala/com/ossuminc/riddl/hugo/MarkdownWriter.scala, hugo/src/main/scala/com/ossuminc/riddl/hugo/ToDoListPass.scala, language/src/main/scala/com/ossuminc/riddl/language/AST.scala, language/src/main/scala/com/ossuminc/riddl/language/At.scala, language/src/main/scala/com/ossuminc/riddl/language/parsing/CommonParser.scala, passes/src/main/scala/com/ossuminc/riddl/passes/resolve/ResolutionPass.scala, passes/src/main/scala/com/ossuminc/riddl/passes/resolve/UsageResolution.scala, passes/src/main/scala/com/ossuminc/riddl/passes/validate/ValidationPass.scala, prettify/src/main/scala/com/ossuminc/riddl/prettify/RiddlFileEmitter.scala, project/plugins.sbt, stats/src/main/scala/com/ossuminc/riddl/stats/StatsPass.scala, testkit/src/main/scala/com/ossuminc/riddl/testkit/ValidatingTest.scala, utils/src/main/scala/com/ossuminc/riddl/utils/Interrupt.scala, utils/src/main/scala/com/ossuminc/riddl/utils/Logger.scala, utils/src/main/scala/com/ossuminc/riddl/utils/PathUtils.scala, utils/src/main/scala/com/ossuminc/riddl/utils/Plugin.scala, utils/src/main/scala/com/ossuminc/riddl/utils/PluginClassLoader.scala, utils/src/main/scala/com/ossuminc/riddl/utils/StringHelpers.scala, utils/src/main/scala/com/ossuminc/riddl/utils/Tar.scala, utils/src/main/scala/com/ossuminc/riddl/utils/TextFileWriter.scala, utils/src/test/scala/com/ossuminc/riddl/utils/InterruptTest.scala
WartRemover was determined to not support Scala 3 well. Neither does Scalafix for that matter.
Simply pull out all the WartRemover @SuppressWarning annotations and wait for the tools to catch up.
=> Remove all @SuppressWarning and prepare for Scalafix

commands/src/main/scala/com/ossuminc/riddl/commands/CommandOptions.scala, language/src/main/scala/com/ossuminc/riddl/language/parsing/ParsingContext.scala, language/src/main/scala/com/ossuminc/riddl/language/parsing/TopLevelParser.scala
Fixes some time-out issues because of using Java's Executor not Scala's ExecutionContext. 
Also made it avoid using Futures/parallelism at all if maxParallelParsing is < 2
=> Parallel Include Improvements

commands/src/main/scala/com/ossuminc/riddl/commands/CommandOptions.scala, commands/src/main/scala/com/ossuminc/riddl/commands/CommandPlugin.scala, commands/src/main/scala/com/ossuminc/riddl/commands/CommonOptionsHelper.scala
The group-by-message-kind option is being ignored. This PR fixes that by making sure the correct commonOptions value is being used when the `from` command uses CommandPlugin.runFromConfit
=> Fix group by kind option

commands/src/main/scala/com/ossuminc/riddl/commands/CommandPlugin.scala, hugo/src/test/scala/com/ossuminc/riddl/hugo/HugoPassTest.scala, riddlc/src/test/scala/com/ossuminc/riddl/RunHugoOnExamplesTest.scala, testkit/src/main/scala/com/ossuminc/riddl/testkit/RunCommandOnExamplesTest.scala
warnings and infos were not being printed when a hugo or validate command was run via from. This fixes that.
=> Fix lack of non error messages

build.sbt, language/jvm/src/test/scala/com/ossuminc/riddl/language/ASTTestJVM.scala, language/shared/src/main/scala/com/ossuminc/riddl/language/AST.scala, language/shared/src/main/scala/com/ossuminc/riddl/language/parsing/CommonParser.scala, language/shared/src/main/scala/com/ossuminc/riddl/language/parsing/Keywords.scala, language/shared/src/test/scala/com/ossuminc/riddl/language/ASTAccessTest.scala, language/shared/src/test/scala/com/ossuminc/riddl/language/ASTTest.scala, passes/shared/src/main/scala/com/ossuminc/riddl/passes/prettify/RiddlFileEmitter.scala, passes/shared/src/main/scala/com/ossuminc/riddl/passes/validate/DefinitionValidation.scala, project/Dependencies.scala
Allow:
* attachments in files or strings
* each attachment has a mime type
* ulids are handled specially to auto-create the attachment when you ask for the ulid value via an API method
=> Implement ULID support

language/jvm/src/test/scala/com/ossuminc/riddl/language/parsing/TopLevelParserTest.scala, language/shared/src/main/scala/com/ossuminc/riddl/language/parsing/ExtensibleTopLevelParser.scala, language/shared/src/main/scala/com/ossuminc/riddl/language/parsing/ParsingContext.scala, language/shared/src/main/scala/com/ossuminc/riddl/language/parsing/TopLevelParser.scala, language/shared/src/test/scala/com/ossuminc/riddl/language/parsing/AbstractParsingTest.scala, language/shared/src/test/scala/com/ossuminc/riddl/language/parsing/TestParser.scala, passes/shared/src/main/scala/com/ossuminc/riddl/passes/validate/BasicValidation.scala
* ParserContext just keeps a list of every file imported.
* New method TopLevelParser.parseRootWithURLs
* Abstract out ExtensibleTopLevelParser
* Eliminate code redundancy in TopLevelParser
=> Implement capturing URLs during parsing
